stages:
  - build 
  - test
  - deploy

build_docker_image:
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: build
  script:
    - docker build -f melodic.Dockerfile --build-arg GIT_COMMIT=$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA

test_environments: 
  stage: test
  variables:
    ROBOT_SERVERS_IMAGE: $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA
  trigger:
    project: robo-gym/robo-gym
    strategy: depend
  except:
    - /^capsize.*$/

test_capsize_environments:
  stage: test
  trigger:
    project: robo-gym/robo-gym
    branch: capsize_master
    strategy: depend
  only:
    - /^capsize.*$/

deploy_develop_docker_image:
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/develop:latest
    - docker push $CI_REGISTRY_IMAGE/develop:latest
  only:
    - develop

deploy_master_docker_image:
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/master:latest
    - docker push $CI_REGISTRY_IMAGE/master:latest
    - docker tag $CI_REGISTRY_IMAGE/master:latest joanneumrobotics/robo-gym-robot-server-side:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/master:latest joanneumrobotics/robo-gym-robot-server-side:latest
    - echo "$DOCKER_HUB_TOKEN" | docker login --username $DOCKER_HUB_USER --password-stdin
    - docker push joanneumrobotics/robo-gym-robot-server-side:$CI_COMMIT_SHA
    - docker push joanneumrobotics/robo-gym-robot-server-side:latest
  only:
    - master

deploy_manual_docker_image:
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/manual_deploy:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/manual_deploy:$CI_COMMIT_SHA
  when: manual

deploy_capsize_master_docker_image:
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/capsize_master:latest
    - docker push $CI_REGISTRY_IMAGE/capsize_master:latest
  only:
    - capsize_master

deploy_capsize_develop_docker_image:
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/rs:dev-$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/capsize_develop:latest
    - docker push $CI_REGISTRY_IMAGE/capsize_develop:latest
  only:
    - capsize_develop

